### ISSUE TITLE
newpaper causes error in treesitter

### ISSUE THREAD

**Issue by p-mackay** [yorik1984/newpaper.nvim#11]
Running :checkhealth nvim-treesitter
.
.
.
The following errors have been detected: ~
- ERROR vimdoc(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 84:4. Invalid node type "delimiter":
    (delimiter) @markup.raw.delimiter
     ^
  
  vimdoc(highlights) is concatenated from the following files:
  |    [OK]:"/home/michael/.local/share/nvim/lazy/nvim-treesitter/queries/vimdoc/highlights.scm"
  | [ERROR]:"/home/michael/.local/share/nvim/lazy/**newpaper.nvim**/after/queries/vimdoc/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 26:4. Invalid node type "delimiter":
    (delimiter) @markup.raw.delimiter
     ^
Removing newpaper fixes this error.

**Comment by yorik1984** [comment]
try
`:TSUpdate vimdoc`

**Comment by p-mackay** [comment]
I'm using https://github.com/nvim-lua/kickstart.nvim not sure if this error happens with the default config. I haven't changed much in the config. 
Output of the command says parser's are up to date. When I run any command I get the following error:
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:178: in function 'prepare_highlight_states'
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:405: in f
Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 84:4. Invalid node type "delimiter":
  (delimiter) @markup.raw.delimiter
   ^

**Comment by yorik1984** [comment]
https://github.com/neovim/tree-sitter-vimdoc/commit/1b177bd9f53995dac83616e84b552a8d4f6c5f7e#diff-19f4fcfba4f0bf0e329d560db476e0fa05262df4c1d6e18c728bc26da754537aR16
Node type "delimiter" was added a few months ago. Maybe you use old version of some files?
What neovim version?

**Comment by p-mackay** [comment]
Yes thank you, I did `rm -rf ~/.local/share/nvim/` then lazy re-installed everything. Not getting the error anymore.
