### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by arvindchoudhary33** [yorik1984/newpaper.nvim#3]
lualine_style  = "light",

Repeated twice in default config for lua ( second last row )

Also for NVIM (v0.7.2)  ( getting this error ) 
Option 'contrast_sidebar' does not exists 
am not sure how to use it. contrast_sidebar = {}

Is there any support for nvim ( transparent bg )?. 
Unable to do it.

**Comment by yorik1984** [comment]
Sorry, doc contains deprecated options. Fix in  1054a9c27404d2c9ac5c1543440d51ffda7148dc
For transparent bg you can use option:
```
require("newpaper").setup({
    disable_background  = true,
)}
```
or use more improvement configuration plugin to control many options https://github.com/xiyaowong/nvim-transparent
