### ISSUE TITLE
[request] Respect background option

### ISSUE THREAD

**Issue by Slotos** [yorik1984/newpaper.nvim#5]
Background option is intended to be used as a source of information for colorschemes. It is a hint about environment Neovim is running in.

To quote `:h background`
> 	This option does NOT change the background color, _it tells Nvim what
	the "inherited" (terminal/GUI) background looks like._

Emphasis mine.

All colorschemes need to do is read the background option. No change detection is necessary, as
> 	When a color scheme is loaded (the "g:colors_name" variable is set)
	setting 'background' will cause the color scheme to be reloaded.  If
	the color scheme adjusts to the value of 'background' this will work.

As a bonus, this will always load variant that matches terminal.

**Comment by yorik1984** [comment]
Default background of neovim is dark. Default background of newpaper colorsheme is light. It always switch to light mode by default. If want dark use option:
`require("newpaper").setup({
    style = "dark"
})`

**Comment by Slotos** [comment]
> Default background of neovim is dark.

That is simply not true. Neovim queries terminal and sets its background value accordinly.

_This comment is not a request to reconsider. Your code, your rules._

**Comment by yorik1984** [comment]
fix in #12
